### PR TITLE
Add support for back/forward keyboard buttons.

### PR DESCRIPTION
**Pull request by dmcbride**

### CODE REVIEW

**Comment by lanurmi** [comment]
Looks good otherwise, but this commit adds a dependency to XF86, which we didn't have before. That would most likely prevent compilation on e.g. Solaris. The changes should be enclosed within an `#ifdef` blocks instead.

I guess `#ifdef __linux__` would be good enough in practice, but if you can find a macro to detect XF86 without including anything XF86-specific first, that would be even better.

**Comment by lanurmi** [comment]
As an additional note; you can add these changes to the current commit by amending it and force-pushing your branch.

**Comment by dmcbride** [comment]
According to http://theunixguys.com/cgi-bin/sunpkg/index.cgi?detail=SUNWxwinc -- XF86keysym.h is present in Solaris 10 (which came out in 2005, so I think we're safe here).  In fact, all my googling shows that xf86 header files are generally available on all x11 systems.

**Comment by lanurmi** [comment]
Okay, seems safe in 2016. I'll merge the PR, with the disclaimer that if I ever come across a platform where compilation fails because of XF86keysym.h, I might simply revert this commit.

**Comment by dmcbride** [comment]
If we find such a platform, we may have enough information at that time to figure out how to #if it out properly.

**Pull request merged**
