### PR TITLE
Copy h_perl from upstream fte project.

### PR DESCRIPTION
**Pull request by dmcbride**
Seeing as upstream is dead (and I'm one of the owners of that project), I'm going to see if I can help here instead.  I've made a ton of changes to fte around its perl support - my primary language.  It doesn't appear that you've made any significant changes since forking, so I'd like to see if you'd be willing to take my changes en masse.  And then I'll continue making perl changes from here, and that way, when I do use other languages, I'll be able to also gain from other work you've done elsewhere.

Thanks,

### CODE REVIEW

**Comment by dmcbride** [comment]
Also, please do not re-style this code (I know it's not up to whatever tool you use), I have more changes to make after this is accepted, so it'll be easier to run your tool after all of the changes are made.

Thanks,

**Comment by lanurmi** [comment]
Hello,

thank you for the contribution! It made me realize the original FTE project has been to some extent alive after eFTE was forked, so there could be other useful things to cherry-pick from there as well.

Looking at your pull request, the first thing to get my attention was that it removes a Copyright line at the top, which is obviously not a good thing. And the second thing I was going to mention is indeed re-styling.

I would say the proper tool for indenting code within this project would be eFTE itself. Admittedly `h_perl.cpp` in master doesn't quite conform to this style. As for other changes, your PR seems to contain quite many whitespace/newline changes, which do not match the traditional FTE coding style. It also becomes harder to see what are the actual changes, and the commit message doesn't really say either. So what does this commit actually do, in short?

I'm looking forward to your further improvements, yet I'm hesitant to accept meaningless whitespace changes in the same commit with actual changes. Git makes it easy to commit only parts of a file, and there shouldn't be a compelling reason to dump whole files as-is from upstream.

**Comment by dmcbride** [comment]
Ok, we can put the copyright back, but I was hoping for functionality prior to aesthetics ;)

And you're right - there are a LOT of changes.  While git can make committing just parts easy, what was difficult was tearing apart the pieces from upstream into their original commits.  I tried various tools to get a dump of the cvs repository, so I could get all the pieces individually, but failed miserably.

It was not my intention to make formatting changes with functional changes - in fact, it's not my intention to reformat the code at all.  However, since perl is my primary language, and I wanted to gain all the work you've done since forking for any other language I might be using, I wanted to get all that missing functionality back asap.  Even then, there are a number of situations that didn't want to highlight properly, so I've been working hard to fix those as well (I think I've finally got that done).

So, my proposal is to accept these changes, and then we can reformat everything again afterwards.  Looking at the git logs, it appears you ran a tool to reformat everything, so I was hoping you could do so after these PRs are caught up.

Submitting all of this is merely part of my yak shaving, my real goal is to work with certain perl code in another github repository that FTE/eFTE didn't highlight properly to make it feasible to update.  Other features I had added to FTE itself will get separate PRs and hopefully be more piecemeal, but I was definitely in a hurry here.

**Comment by lanurmi** [comment]
I have not forgotten this PR, but at its current state it will require at least some reordering and squashing of commits. Also the first commit's message still doesn't tell what does the commit actually change.

If there are more closely related commits to Perl support coming, it may be best to do them in this branch too, before merging.

**Comment by dmcbride** [comment]
I'm not sure what you need done here.  As to the first commit, you're right - it's what I've said since the beginning - I don't have a trivial record of all the changes made to this file over time, just that they were made, and this is importing all of those changes.  As to reordering/squashing, I don't normally do those types of things with git, so, while I'm sure I could figure out the technical _how_ to do that, it's the _what_ (and _why_) that I'm not sure of and thus don't know what would fill your requirements.

**Comment by lanurmi** [comment]
The great thing about Git is that you can change history. So for example, if you add something in commit A, but later realize something's missing, you can modify commit A even if it's not the most recent commit in the branch. Squashing a commit means combining its content to the previous one. And since commits (that do not touch the same lines) can be reordered, any two commits can be made consecutive, and then squashed. Reordering, squashing, editing, and all that is done using [interactive rebase](https://help.github.com/articles/about-git-rebase/).

In this PR, at least 36f0621 and 01326e3 look like commits that correct some unintentional error in a previous commit, so they should be squashed, i.e. make them look like the error never happened.

The *why* part is keeping the history clean, so that the log is more like *"Fix X, Fix Y, Fix Z"* than *"Fix X, oops-forgot-something, Fix Y, oops-still-missing-something-in-X, Fix Z"*. In some cases that also helps towards the goal of keeping each commit in the log in a compilable state.

**Comment by dmcbride** [comment]
ok, I hope I have this in a more-acceptable format for merging.  Thanks for your patience.

**Comment by lanurmi** [comment]
Okay, now it looks good. Thank you, and sorry for the latest delay in merging.

**Pull request merged**
